#!/usr/bin/env bash
#bash script that displays best school 10 times but adds hi on a particular line

count=1
while [ $count -le 10 ]
do 
if [ $count -eq 9 ]; then
echo "Best School"
echo "Hi"
else 
	echo "Best School"
fi
((count++))
done
